-- ===================================================================
-- MIGRATION V1: ESQUEMA INICIAL DA BIBLIONETECA (ORACLE DB)
-- ===================================================================

-- 1. TABELAS DE DOMÍNIO PRINCIPAL E CATÁLOGO

CREATE TABLE AUTHORS
(
    ID            VARCHAR2(36) NOT NULL,
    NAME          VARCHAR2(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    DATE_OF_DEATH DATE,
    NATIONALITY   VARCHAR2(255),
    CONSTRAINT PK_AUTHORS PRIMARY KEY (ID)
);

CREATE INDEX IDX_AUTHORS_NAME ON AUTHORS (NAME);


CREATE TABLE BOOKS
(
    ID   VARCHAR2(36) NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_BOOKS PRIMARY KEY (ID)
);

CREATE INDEX IDX_BOOKS_NAME ON BOOKS (NAME);


CREATE TABLE PUBLISHERS
(
    ID         VARCHAR2(36) NOT NULL,
    LEGAL_NAME VARCHAR2(255) NOT NULL,
    TRADE_NAME VARCHAR2(255) NOT NULL,
    CNPJ       VARCHAR2(14) NOT NULL,
    SITE_URL   VARCHAR2(255),
    CONSTRAINT PK_PUBLISHERS PRIMARY KEY (ID),
    CONSTRAINT UK_PUBLISHERS_CNPJ UNIQUE (CNPJ)
);


CREATE TABLE EDITIONS
(
    ID               VARCHAR2(36) NOT NULL,
    ISBN             VARCHAR2(17) NOT NULL, -- Corrigido para NOT NULL (Conforme @NotNull no Java)
    FK_BOOK          VARCHAR2(36) NOT NULL,
    FK_PUBLISHER     VARCHAR2(36) NOT NULL,
    EDITION_NUMBER   NUMBER(5,0),
    YEAR_PUBLICATION NUMBER(5,0) NOT NULL,
    LANGUAGE         VARCHAR2(100) NOT NULL,
    PAGE_NUMBER      NUMBER(5,0) NOT NULL,
    COVER            VARCHAR2(255) NOT NULL, -- Corrigido de 'cover_url' para 'cover' e NOT NULL (Conforme Java)
    SYNOPSIS         CLOB NOT NULL,
    CONSTRAINT PK_EDITIONS PRIMARY KEY (ID),
    CONSTRAINT UK_EDITIONS_ISBN UNIQUE (ISBN)
);


CREATE TABLE AUTHOR_BOOK
(
    FK_AUTHOR VARCHAR2(36) NOT NULL,
    FK_BOOK   VARCHAR2(36) NOT NULL,
    CONSTRAINT PK_AUTHOR_BOOK PRIMARY KEY (FK_AUTHOR, FK_BOOK)
);


-- 2. TABELAS DE ATORES DO SISTEMA (USUÁRIOS)

CREATE TABLE CLIENTS
(
    ID                      VARCHAR2(36) NOT NULL,
    CPF                     VARCHAR2(11) NOT NULL,
    FULL_NAME               VARCHAR2(255) NOT NULL,
    DATE_OF_BIRTH           DATE NOT NULL,
    EMAIL                   VARCHAR2(255),
    CELL_NUMBER             VARCHAR2(20) NOT NULL,
    REGISTRATION_EXPIRATION DATE NOT NULL,
    CONSTRAINT PK_CLIENTS PRIMARY KEY (ID),
    CONSTRAINT UK_CLIENTS_CPF UNIQUE (CPF),
    CONSTRAINT UK_CLIENTS_EMAIL UNIQUE (EMAIL)
);


CREATE TABLE LIBRARIANS
(
    ID            VARCHAR2(36) NOT NULL,
    PASSWORD      VARCHAR2(255) NOT NULL,
    FULL_NAME     VARCHAR2(255) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    CPF           VARCHAR2(11) NOT NULL,
    EMAIL         VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_LIBRARIANS PRIMARY KEY (ID),
    CONSTRAINT UK_LIBRARIANS_CPF UNIQUE (CPF),
    CONSTRAINT UK_LIBRARIANS_EMAIL UNIQUE (EMAIL)
);


-- 3. TABELAS DE INVENTÁRIO FÍSICO E OPERACIONAL (EMPRÉSTIMOS)

CREATE TABLE PHYSICAL_COPIES
(
    ID         VARCHAR2(36) NOT NULL,
    FK_EDITION VARCHAR2(36) NOT NULL,
    ASSET_CODE VARCHAR2(50) NOT NULL,
    STATUS     VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    CONSTRAINT PK_PHYSICAL_COPIES PRIMARY KEY (ID),
    CONSTRAINT UK_PHYSICAL_ASSET_CODE UNIQUE (ASSET_CODE),
    CONSTRAINT CHK_PHYSICAL_STATUS CHECK (STATUS IN ('AVAILABLE', 'LOANED', 'LOST', 'MAINTENANCE'))
);


CREATE TABLE LOANS
(
    ID               VARCHAR2(36) NOT NULL,
    FK_LIBRARIAN     VARCHAR2(36) NOT NULL,
    FK_PHYSICAL_COPY VARCHAR2(36) NOT NULL,
    FK_CLIENT        VARCHAR2(36) NOT NULL,
    DATE_LOAN        DATE DEFAULT SYSDATE NOT NULL,
    DUE_DATE         DATE                 NOT NULL,
    DATE_RETURN      DATE,
    RENEWAL          NUMBER(5,0) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_LOANS PRIMARY KEY (ID)
);


-- ===================================================================
-- 4. CHAVES ESTRANGEIRAS (RELACIONAMENTOS)
-- ===================================================================

ALTER TABLE EDITIONS
    ADD CONSTRAINT FK_EDITIONS_BOOK FOREIGN KEY (FK_BOOK) REFERENCES BOOKS (ID);

ALTER TABLE EDITIONS
    ADD CONSTRAINT FK_EDITIONS_PUBLISHER FOREIGN KEY (FK_PUBLISHER) REFERENCES PUBLISHERS (ID);

ALTER TABLE AUTHOR_BOOK
    ADD CONSTRAINT FK_AB_AUTHOR FOREIGN KEY (FK_AUTHOR) REFERENCES AUTHORS (ID);

ALTER TABLE AUTHOR_BOOK
    ADD CONSTRAINT FK_AB_BOOK FOREIGN KEY (FK_BOOK) REFERENCES BOOKS (ID);

ALTER TABLE PHYSICAL_COPIES
    ADD CONSTRAINT FK_PHYSICAL_EDITION FOREIGN KEY (FK_EDITION) REFERENCES EDITIONS (ID);

ALTER TABLE LOANS
    ADD CONSTRAINT FK_LOANS_LIBRARIAN FOREIGN KEY (FK_LIBRARIAN) REFERENCES LIBRARIANS (ID);

ALTER TABLE LOANS
    ADD CONSTRAINT FK_LOANS_PHYSICAL_COPY FOREIGN KEY (FK_PHYSICAL_COPY) REFERENCES PHYSICAL_COPIES (ID);

ALTER TABLE LOANS
    ADD CONSTRAINT FK_LOANS_CLIENT FOREIGN KEY (FK_CLIENT) REFERENCES CLIENTS (ID);


-- ===================================================================
-- 5. ÍNDICES DE PERFORMANCE PARA CHAVES ESTRANGEIRAS
-- ===================================================================

CREATE INDEX IDX_EDITIONS_FK_BOOK ON EDITIONS (FK_BOOK);
CREATE INDEX IDX_EDITIONS_FK_PUB ON EDITIONS (FK_PUBLISHER);

CREATE INDEX IDX_AB_FK_AUTHOR ON AUTHOR_BOOK (FK_AUTHOR);
CREATE INDEX IDX_AB_FK_BOOK ON AUTHOR_BOOK (FK_BOOK);

CREATE INDEX IDX_PHYSICAL_FK_EDITION ON PHYSICAL_COPIES (FK_EDITION);

CREATE INDEX IDX_LOANS_FK_LIB ON LOANS (FK_LIBRARIAN);
CREATE INDEX IDX_LOANS_FK_COPY ON LOANS (FK_PHYSICAL_COPY);
CREATE INDEX IDX_LOANS_FK_CLIENT ON LOANS (FK_CLIENT);