-- ===================================================================
-- MIGRATION V2: ADIÇÃO DE GÊNEROS, RENOMEAÇÃO DE COLUNAS E FKs DEFERRÁVEIS
-- ===================================================================

-- 1. RENOMEAÇÃO DA COLUNA NAME PARA TITLE NA TABELA BOOKS E ATUALIZAÇÃO DO ÍNDICE
-- (O Oracle permite renomear a coluna diretamente. Primeiro, dropamos o índice antigo).
DROP INDEX IDX_BOOKS_NAME;
ALTER TABLE BOOKS
    RENAME COLUMN NAME TO TITLE;
CREATE INDEX IDX_BOOKS_TITLE ON BOOKS (TITLE);


-- 2. CRIAÇÃO DAS NOVAS TABELAS DE GÊNEROS
CREATE TABLE GENRES
(
    ID   VARCHAR2(36)  NOT NULL,
    NAME VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_GENRES PRIMARY KEY (ID)
);

CREATE INDEX IDX_GENRES_NAME ON GENRES (NAME);

CREATE TABLE BOOK_GENRE
(
    FK_BOOK  VARCHAR2(36) NOT NULL,
    FK_GENRE VARCHAR2(36) NOT NULL,
    CONSTRAINT PK_BOOK_GENRE PRIMARY KEY (FK_BOOK, FK_GENRE)
);

CREATE INDEX IDX_BG_FK_BOOK ON BOOK_GENRE (FK_BOOK);
CREATE INDEX IDX_BG_FK_GENDER ON BOOK_GENRE (FK_GENRE);


-- 3. ATUALIZAR AS FOREIGN KEYS EXISTENTES PARA "DEFERRABLE INITIALLY IMMEDIATE"
-- Para alterar restrições no Oracle, é necessário removê-las e recriá-las.

ALTER TABLE EDITIONS
    DROP CONSTRAINT FK_EDITIONS_BOOK;
ALTER TABLE EDITIONS
    DROP CONSTRAINT FK_EDITIONS_PUBLISHER;
ALTER TABLE AUTHOR_BOOK
    DROP CONSTRAINT FK_AB_AUTHOR;
ALTER TABLE AUTHOR_BOOK
    DROP CONSTRAINT FK_AB_BOOK;
ALTER TABLE PHYSICAL_COPIES
    DROP CONSTRAINT FK_PHYSICAL_EDITION;
ALTER TABLE LOANS
    DROP CONSTRAINT FK_LOANS_LIBRARIAN;
ALTER TABLE LOANS
    DROP CONSTRAINT FK_LOANS_PHYSICAL_COPY;
ALTER TABLE LOANS
    DROP CONSTRAINT FK_LOANS_CLIENT;

-- Recriando as Foreign Keys antigas com a nova regra
ALTER TABLE EDITIONS
    ADD CONSTRAINT FK_EDITIONS_BOOK FOREIGN KEY (FK_BOOK) REFERENCES BOOKS (ID) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE EDITIONS
    ADD CONSTRAINT FK_EDITIONS_PUBLISHER FOREIGN KEY (FK_PUBLISHER) REFERENCES PUBLISHERS (ID) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE AUTHOR_BOOK
    ADD CONSTRAINT FK_AB_AUTHOR FOREIGN KEY (FK_AUTHOR) REFERENCES AUTHORS (ID) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE AUTHOR_BOOK
    ADD CONSTRAINT FK_AB_BOOK FOREIGN KEY (FK_BOOK) REFERENCES BOOKS (ID) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE PHYSICAL_COPIES
    ADD CONSTRAINT FK_PHYSICAL_EDITION FOREIGN KEY (FK_EDITION) REFERENCES EDITIONS (ID) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE LOANS
    ADD CONSTRAINT FK_LOANS_LIBRARIAN FOREIGN KEY (FK_LIBRARIAN) REFERENCES LIBRARIANS (ID) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE LOANS
    ADD CONSTRAINT FK_LOANS_PHYSICAL_COPY FOREIGN KEY (FK_PHYSICAL_COPY) REFERENCES PHYSICAL_COPIES (ID) DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE LOANS
    ADD CONSTRAINT FK_LOANS_CLIENT FOREIGN KEY (FK_CLIENT) REFERENCES CLIENTS (ID) DEFERRABLE INITIALLY IMMEDIATE;


-- 4. ADICIONAR AS FOREIGN KEYS DA NOVA TABELA BOOK_GENRE
ALTER TABLE BOOK_GENRE
    ADD CONSTRAINT FK_BG_BOOK FOREIGN KEY (FK_BOOK) REFERENCES BOOKS (ID) DEFERRABLE INITIALLY IMMEDIATE;

-- Nota: No seu script V2 original estava FK_AB_GENDER, corrigi para FK_BG_GENRE para manter o padrão.
ALTER TABLE BOOK_GENRE
    ADD CONSTRAINT FK_BG_GENRE FOREIGN KEY (FK_GENRE) REFERENCES GENRES (ID) DEFERRABLE INITIALLY IMMEDIATE;