# Conexão com o Oracle Database
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=seu_usuario_oracle
spring.datasource.password=sua_senha_oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Dialeto específico para o Oracle Database
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update