# Conexão com o Postgres no Docker (seu Homelab)
spring.datasource.url=${DB_POSTGRES_URL:jdbc:postgresql://localhost:5432/biblioneteca-db}
spring.datasource.username=${DB_POSTGRES_USER:postgres}
spring.datasource.password=${DB_POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialeto específico para o Postgres traduzir o SQL do JPA corretamente
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ddl-auto configurado para atualizar/criar tabelas automaticamente em desenvolvimento
spring.jpa.hibernate.ddl-auto=update