spring.application.name=biblioneteca
# Configurações globais do Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

# Perfil padrão ativo se você não especificar nenhum ao rodar (Postgres)
spring.profiles.active=postgres,dev