# Conexão com o Oracle Database
spring.datasource.url=${DB_ORACLE_URL}
spring.datasource.username=${DB_ORACLE_USER}
spring.datasource.password=${DB_ORACLE_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Dialeto específico para o Oracle Database
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

spring.jpa.hibernate.ddl-auto=update